In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
Independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [6]:
Dependent=dataset[["charges"]]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

In [8]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 1.0/101.7 MB 5.7 MB/s eta 0:00:18
    --------------------------------------- 1.8/101.7 MB 3.5 MB/s eta 0:00:29
   - -------------------------------------- 2.6/101.7 MB 3.6 MB/s eta 0:00:28
   - -------------------------------------- 3.1/101.7 MB 3.5 MB/s eta 0:00:29
   - -------------------------------------- 4.2/101.7 MB 3.7 MB/s eta 0:00:27
   -- ------------------------------------- 5.5/101.7 MB 4.1 MB/s eta 0:00:24
   -- ------------------------------------- 6.0/101.7 MB 4.3 MB/s eta 0:00:23
   -- ------------------------------------- 6.3/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.8/101.7 MB 3.5 MB/s eta 0:00:28
   -- ------------------------------------- 7.3/101.7 MB 3.3 MB/s eta 0:00:29
   --- ------------------------------------ 7.9/101.7 MB 3.3 MB/s eta 0:00:29
   --- ------------------------------------ 8.1/101.7 MB 3.2 MB/s eta 0:00:29
   --- ------------------------------------ 8.4/101.7 MB 3.1 MB/s eta 0:00:30
   --- ------------------------------------ 9.2/101.7 MB 3.0 MB/s eta 0:00:31
   --- ------------------------------------ 9.7/101.7 MB 3.0 MB/s eta 0:00:31
   ---- ----------------------------------- 10.2/101.7 MB 2.9 MB/s eta 0:00:32
   ---- ----------------------------------- 10.7/101.7 MB 2.9 MB/s eta 0:00:31
   ---- ----------------------------------- 11.5/101.7 MB 3.0 MB/s eta 0:00:31
   ---- ----------------------------------- 12.6/101.7 MB 3.1 MB/s eta 0:00:30
   ----- ---------------------------------- 13.1/101.7 MB 3.1 MB/s eta 0:00:29
   ----- ---------------------------------- 13.6/101.7 MB 3.0 MB/s eta 0:00:29
   ----- ---------------------------------- 14.4/101.7 MB 3.0 MB/s eta 0:00:29
   ----- ---------------------------------- 15.2/101.7 MB 3.1 MB/s eta 0:00:29
   ------ --------------------------------- 15.7/101.7 MB 3.1 MB/s eta 0:00:28
   ------ --------------------------------- 16.0/101.7 MB 3.1 MB/s eta 0:00:29
   ------ --------------------------------- 16.8/101.7 MB 3.1 MB/s eta 0:00:28
   ------ --------------------------------- 17.6/101.7 MB 3.1 MB/s eta 0:00:28
   ------- -------------------------------- 18.4/101.7 MB 3.1 MB/s eta 0:00:28
   ------- -------------------------------- 19.1/101.7 MB 3.1 MB/s eta 0:00:27
   ------- -------------------------------- 19.7/101.7 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 20.4/101.7 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 21.0/101.7 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 21.8/101.7 MB 3.1 MB/s eta 0:00:26
   -------- ------------------------------- 22.3/101.7 MB 3.1 MB/s eta 0:00:26
   -------- ------------------------------- 22.8/101.7 MB 3.1 MB/s eta 0:00:26
   --------- ------------------------------ 23.3/101.7 MB 3.1 MB/s eta 0:00:26
   --------- ------------------------------ 23.9/101.7 MB 3.0 MB/s eta 0:00:26
   --------- ------------------------------ 24.6/101.7 MB 3.0 MB/s eta 0:00:26
   --------- ------------------------------ 25.2/101.7 MB 3.0 MB/s eta 0:00:26
   ---------- ----------------------------- 26.0/101.7 MB 3.0 MB/s eta 0:00:25
   ---------- ----------------------------- 26.5/101.7 MB 3.0 MB/s eta 0:00:25
   ---------- ----------------------------- 27.0/101.7 MB 3.0 MB/s eta 0:00:25
   ---------- ----------------------------- 27.5/101.7 MB 3.0 MB/s eta 0:00:25
   ----------- ---------------------------- 28.0/101.7 MB 3.0 MB/s eta 0:00:25
   ----------- ---------------------------- 28.8/101.7 MB 3.0 MB/s eta 0:00:25
   ----------- ---------------------------- 29.4/101.7 MB 3.0 MB/s eta 0:00:25
   ----------- ---------------------------- 29.9/101.7 MB 3.0 MB/s eta 0:00:24
   ------------ --------------------------- 30.7/101.7 MB 3.0 MB/s eta 0:00:24
   ------------ --------------------------- 31.2/101.7 MB 3.0 MB/s eta 0:00:24
   ------------ --------------------------- 32.0/101.7 MB 3.0 MB/s eta 0:00:24
   ------------ --------------------------- 32.8/101.7 MB 3.0 MB/s eta 0:00:23
   ------------- -------------------------- 33.6/101.7 MB 3.0 MB/s eta 0:00:23
   ------------- -------------------------- 33.8/101.7 MB 3.0 MB/s eta 0:00:23
   ------------- -------------------------- 34.1/101.7 MB 3.0 MB/s eta 0:00:23
   ------------- -------------------------- 34.9/101.7 MB 3.0 MB/s eta 0:00:23
   ------------- -------------------------- 35.4/101.7 MB 3.0 MB/s eta 0:00:23
   -------------- ------------------------- 35.9/101.7 MB 3.0 MB/s eta 0:00:23
   -------------- ------------------------- 36.4/101.7 MB 3.0 MB/s eta 0:00:23
   -------------- ------------------------- 36.7/101.7 MB 2.9 MB/s eta 0:00:23
   -------------- ------------------------- 37.2/101.7 MB 2.9 MB/s eta 0:00:23
   -------------- ------------------------- 37.7/101.7 MB 2.9 MB/s eta 0:00:22
   --------------- ------------------------ 38.3/101.7 MB 2.9 MB/s eta 0:00:22
   --------------- ------------------------ 38.8/101.7 MB 2.9 MB/s eta 0:00:22
   --------------- ------------------------ 39.3/101.7 MB 2.9 MB/s eta 0:00:22
   --------------- ------------------------ 39.6/101.7 MB 2.9 MB/s eta 0:00:22
   --------------- ------------------------ 40.1/101.7 MB 2.9 MB/s eta 0:00:22
   --------------- ------------------------ 40.6/101.7 MB 2.9 MB/s eta 0:00:22
   ---------------- ----------------------- 41.4/101.7 MB 2.9 MB/s eta 0:00:22
   ---------------- ----------------------- 41.9/101.7 MB 2.9 MB/s eta 0:00:21
   ---------------- ----------------------- 42.7/101.7 MB 2.9 MB/s eta 0:00:21
   ----------------- ---------------------- 43.3/101.7 MB 2.9 MB/s eta 0:00:21
   ----------------- ---------------------- 43.8/101.7 MB 2.9 MB/s eta 0:00:21
   ----------------- ---------------------- 44.6/101.7 MB 2.9 MB/s eta 0:00:20
   ----------------- ---------------------- 45.1/101.7 MB 2.9 MB/s eta 0:00:20
   ------------------ --------------------- 46.1/101.7 MB 2.9 MB/s eta 0:00:20
   ------------------ --------------------- 46.7/101.7 MB 2.9 MB/s eta 0:00:20
   ------------------ --------------------- 47.4/101.7 MB 2.9 MB/s eta 0:00:19
   ------------------ --------------------- 48.2/101.7 MB 2.9 MB/s eta 0:00:19
   ------------------- -------------------- 48.8/101.7 MB 2.9 MB/s eta 0:00:19
   ------------------- -------------------- 49.5/101.7 MB 2.9 MB/s eta 0:00:18
   ------------------- -------------------- 50.3/101.7 MB 2.9 MB/s eta 0:00:18
   -------------------- ------------------- 51.1/101.7 MB 2.9 MB/s eta 0:00:18
   -------------------- ------------------- 51.6/101.7 MB 2.9 MB/s eta 0:00:18
   -------------------- ------------------- 52.2/101.7 MB 2.9 MB/s eta 0:00:17
   -------------------- ------------------- 52.4/101.7 MB 2.9 MB/s eta 0:00:17
   -------------------- ------------------- 53.2/101.7 MB 2.9 MB/s eta 0:00:17
   --------------------- ------------------ 53.7/101.7 MB 2.9 MB/s eta 0:00:17
   --------------------- ------------------ 54.5/101.7 MB 2.9 MB/s eta 0:00:17
   --------------------- ------------------ 55.3/101.7 MB 2.9 MB/s eta 0:00:16
   --------------------- ------------------ 55.6/101.7 MB 2.9 MB/s eta 0:00:16
   ---------------------- ----------------- 56.1/101.7 MB 2.9 MB/s eta 0:00:16
   ---------------------- ----------------- 56.6/101.7 MB 2.9 MB/s eta 0:00:16
   ---------------------- ----------------- 57.4/101.7 MB 2.9 MB/s eta 0:00:16
   ---------------------- ----------------- 58.2/101.7 MB 2.9 MB/s eta 0:00:15
   ----------------------- ---------------- 58.7/101.7 MB 2.9 MB/s eta 0:00:15
   ----------------------- ---------------- 59.2/101.7 MB 2.9 MB/s eta 0:00:15
   ----------------------- ---------------- 59.8/101.7 MB 2.9 MB/s eta 0:00:15
   ----------------------- ---------------- 60.6/101.7 MB 2.9 MB/s eta 0:00:15
   ------------------------ --------------- 61.1/101.7 MB 2.9 MB/s eta 0:00:14
   ------------------------ --------------- 61.6/101.7 MB 2.9 MB/s eta 0:00:14
   ------------------------ --------------- 62.1/101.7 MB 2.9 MB/s eta 0:00:14
   ------------------------ --------------- 62.7/101.7 MB 2.9 MB/s eta 0:00:14
   ------------------------ --------------- 63.2/101.7 MB 2.9 MB/s eta 0:00:14
   ------------------------ --------------- 63.4/101.7 MB 2.9 MB/s eta 0:00:14
   ------------------------- -------------- 64.0/101.7 MB 2.9 MB/s eta 0:00:14
   ------------------------- -------------- 64.5/101.7 MB 2.9 MB/s eta 0:00:13
   ------------------------- -------------- 65.0/101.7 MB 2.9 MB/s eta 0:00:13
   ------------------------- -------------- 65.3/101.7 MB 2.9 MB/s eta 0:00:13
   ------------------------- -------------- 65.8/101.7 MB 2.9 MB/s eta 0:00:13
   -------------------------- ------------- 66.3/101.7 MB 2.8 MB/s eta 0:00:13
   -------------------------- ------------- 66.6/101.7 MB 2.8 MB/s eta 0:00:13
   -------------------------- ------------- 67.1/101.7 MB 2.8 MB/s eta 0:00:13
   -------------------------- ------------- 68.2/101.7 MB 2.8 MB/s eta 0:00:12
   --------------------------- ------------ 68.9/101.7 MB 2.8 MB/s eta 0:00:12
   --------------------------- ------------ 69.5/101.7 MB 2.9 MB/s eta 0:00:12
   --------------------------- ------------ 70.0/101.7 MB 2.9 MB/s eta 0:00:12
   --------------------------- ------------ 70.8/101.7 MB 2.9 MB/s eta 0:00:11
   ---------------------------- ----------- 71.3/101.7 MB 2.9 MB/s eta 0:00:11
   ---------------------------- ----------- 72.1/101.7 MB 2.9 MB/s eta 0:00:11
   ---------------------------- ----------- 72.9/101.7 MB 2.9 MB/s eta 0:00:11
   ---------------------------- ----------- 73.7/101.7 MB 2.9 MB/s eta 0:00:10
   ----------------------------- ---------- 74.4/101.7 MB 2.9 MB/s eta 0:00:10
   ----------------------------- ---------- 75.2/101.7 MB 2.9 MB/s eta 0:00:10
   ----------------------------- ---------- 75.5/101.7 MB 2.9 MB/s eta 0:00:10
   ------------------------------ --------- 76.3/101.7 MB 2.9 MB/s eta 0:00:09
   ------------------------------ --------- 76.8/101.7 MB 2.9 MB/s eta 0:00:09
   ------------------------------ --------- 77.1/101.7 MB 2.9 MB/s eta 0:00:09
   ------------------------------ --------- 77.9/101.7 MB 2.9 MB/s eta 0:00:09
   ------------------------------ --------- 78.1/101.7 MB 2.9 MB/s eta 0:00:09
   ------------------------------- -------- 78.9/101.7 MB 2.9 MB/s eta 0:00:08
   ------------------------------- -------- 79.2/101.7 MB 2.9 MB/s eta 0:00:08
   ------------------------------- -------- 80.0/101.7 MB 2.9 MB/s eta 0:00:08
   ------------------------------- -------- 80.7/101.7 MB 2.9 MB/s eta 0:00:08
   ------------------------------- -------- 81.3/101.7 MB 2.9 MB/s eta 0:00:08
   -------------------------------- ------- 82.3/101.7 MB 2.9 MB/s eta 0:00:07
   -------------------------------- ------- 82.8/101.7 MB 2.9 MB/s eta 0:00:07
   -------------------------------- ------- 83.4/101.7 MB 2.9 MB/s eta 0:00:07
   --------------------------------- ------ 84.1/101.7 MB 2.9 MB/s eta 0:00:07
   --------------------------------- ------ 84.7/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 84.9/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 85.5/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 85.5/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 86.0/101.7 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 86.5/101.7 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 87.0/101.7 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 87.8/101.7 MB 2.8 MB/s eta 0:00:05
   ---------------------------------- ----- 88.1/101.7 MB 2.8 MB/s eta 0:00:05
   ---------------------------------- ----- 88.6/101.7 MB 2.8 MB/s eta 0:00:05
   ---------------------------------- ----- 88.9/101.7 MB 2.8 MB/s eta 0:00:05
   ---------------------------------- ----- 88.9/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 89.4/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 89.9/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 90.4/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 91.0/101.7 MB 2.8 MB/s eta 0:00:04
   ----------------------------------- ---- 91.5/101.7 MB 2.8 MB/s eta 0:00:04
   ------------------------------------ --- 92.0/101.7 MB 2.8 MB/s eta 0:00:04
   ------------------------------------ --- 92.5/101.7 MB 2.8 MB/s eta 0:00:04
   ------------------------------------ --- 92.8/101.7 MB 2.8 MB/s eta 0:00:04
   ------------------------------------ --- 93.3/101.7 MB 2.7 MB/s eta 0:00:04
   ------------------------------------ --- 93.8/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 94.6/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.2/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 96.2/101.7 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 96.5/101.7 MB 2.8 MB/s eta 0:00:02
   -------------------------------------- - 96.7/101.7 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 97.3/101.7 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 97.8/101.7 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 98.3/101.7 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 99.1/101.7 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  99.6/101.7 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  100.7/101.7 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 2.7 MB/s  0:00:37
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [47]:
from xgboost import XGBRegressor
Regressor=XGBRegressor(n_estimators=100,random_state=0)
Regressor=Regressor.fit(x_train,y_train)

In [48]:
y_pred=Regressor.predict(x_test)

In [49]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [50]:
r_score

0.8213337063789368