In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
Independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [5]:
Dependent=dataset[["charges"]]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

In [7]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\anaconda3\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\anaconda3\lib\site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\anaconda3\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in c:\anaconda3\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in c:\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\anaconda3\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\anaconda3\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\anaconda3\lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\anaconda3\lib\site-packages (from plotly->catboost) (2.7.0)
Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/100.2 MB 1.3 MB/s eta 0:01:17
   ---------------------------------------- 1.0/100.2 MB 1.5 MB/s eta 0:01:05
    --------------------------------------- 1.3/100.2 MB 1.7 MB/s eta 0:01:00
    --------------------------------------- 1.8/100.2 MB 1.8 MB/s eta 0:00:56
    --------------------------------------- 2.4/100.2 MB 1.8 MB/s eta 0:00:53
   - -------------------------------------- 2.6/100.2 MB 1.9 MB/s eta 0:00:52
   - -------------------------------------- 3.1/100.2 MB 1.9 MB/s eta 0:00:52
   - -------------------------------------- 3.4/100.2 MB 2.0 MB/s eta 0:00:50
   - -------------------------------------- 3.4/100.2 MB 2.0 MB/s eta 0:00:50
   - -------------------------------------- 3.4/100.2 MB 2.0 MB/s eta 0:00:50
   - -------------------------------------- 3.9/100.2 MB 1.6 MB/s eta 0:01:00
   - -------------------------------------- 4.2/100.2 MB 1.5 MB/s eta 0:01:04
   - -------------------------------------- 4.5/100.2 MB 1.5 MB/s eta 0:01:03
   - -------------------------------------- 5.0/100.2 MB 1.6 MB/s eta 0:01:02
   -- ------------------------------------- 5.2/100.2 MB 1.5 MB/s eta 0:01:02
   -- ------------------------------------- 5.5/100.2 MB 1.5 MB/s eta 0:01:03
   -- ------------------------------------- 5.8/100.2 MB 1.5 MB/s eta 0:01:04
   -- ------------------------------------- 6.0/100.2 MB 1.5 MB/s eta 0:01:02
   -- ------------------------------------- 6.6/100.2 MB 1.5 MB/s eta 0:01:01
   -- ------------------------------------- 6.8/100.2 MB 1.5 MB/s eta 0:01:01
   -- ------------------------------------- 7.3/100.2 MB 1.6 MB/s eta 0:01:00
   --- ------------------------------------ 7.6/100.2 MB 1.6 MB/s eta 0:00:59
   --- ------------------------------------ 8.1/100.2 MB 1.6 MB/s eta 0:00:58
   --- ------------------------------------ 8.4/100.2 MB 1.6 MB/s eta 0:00:57
   --- ------------------------------------ 8.9/100.2 MB 1.6 MB/s eta 0:00:56
   --- ------------------------------------ 9.4/100.2 MB 1.7 MB/s eta 0:00:55
   --- ------------------------------------ 10.0/100.2 MB 1.7 MB/s eta 0:00:54
   ---- ----------------------------------- 10.2/100.2 MB 1.7 MB/s eta 0:00:53
   ---- ----------------------------------- 10.7/100.2 MB 1.7 MB/s eta 0:00:53
   ---- ----------------------------------- 11.0/100.2 MB 1.7 MB/s eta 0:00:53
   ---- ----------------------------------- 11.3/100.2 MB 1.7 MB/s eta 0:00:53
   ---- ----------------------------------- 11.8/100.2 MB 1.7 MB/s eta 0:00:52
   ---- ----------------------------------- 12.3/100.2 MB 1.7 MB/s eta 0:00:51
   ----- ---------------------------------- 13.1/100.2 MB 1.8 MB/s eta 0:00:49
   ----- ---------------------------------- 13.6/100.2 MB 1.8 MB/s eta 0:00:48
   ----- ---------------------------------- 14.2/100.2 MB 1.8 MB/s eta 0:00:47
   ----- ---------------------------------- 14.9/100.2 MB 1.9 MB/s eta 0:00:46
   ------ --------------------------------- 15.5/100.2 MB 1.9 MB/s eta 0:00:46
   ------ --------------------------------- 15.5/100.2 MB 1.9 MB/s eta 0:00:46
   ------ --------------------------------- 15.5/100.2 MB 1.9 MB/s eta 0:00:46
   ------ --------------------------------- 16.0/100.2 MB 1.8 MB/s eta 0:00:47
   ------ --------------------------------- 16.3/100.2 MB 1.8 MB/s eta 0:00:47
   ------ --------------------------------- 16.5/100.2 MB 1.8 MB/s eta 0:00:47
   ------ --------------------------------- 17.0/100.2 MB 1.8 MB/s eta 0:00:47
   ------ --------------------------------- 17.3/100.2 MB 1.8 MB/s eta 0:00:47
   ------- -------------------------------- 17.8/100.2 MB 1.8 MB/s eta 0:00:46
   ------- -------------------------------- 18.4/100.2 MB 1.8 MB/s eta 0:00:46
   ------- -------------------------------- 18.6/100.2 MB 1.8 MB/s eta 0:00:45
   ------- -------------------------------- 19.1/100.2 MB 1.8 MB/s eta 0:00:45
   ------- -------------------------------- 19.4/100.2 MB 1.8 MB/s eta 0:00:45
   ------- -------------------------------- 19.9/100.2 MB 1.8 MB/s eta 0:00:45
   -------- ------------------------------- 20.2/100.2 MB 1.8 MB/s eta 0:00:45
   -------- ------------------------------- 20.2/100.2 MB 1.8 MB/s eta 0:00:45
   -------- ------------------------------- 20.7/100.2 MB 1.8 MB/s eta 0:00:45
   -------- ------------------------------- 21.0/100.2 MB 1.8 MB/s eta 0:00:45
   -------- ------------------------------- 21.2/100.2 MB 1.8 MB/s eta 0:00:45
   -------- ------------------------------- 21.8/100.2 MB 1.8 MB/s eta 0:00:45
   -------- ------------------------------- 22.0/100.2 MB 1.8 MB/s eta 0:00:44
   -------- ------------------------------- 22.3/100.2 MB 1.8 MB/s eta 0:00:44
   -------- ------------------------------- 22.3/100.2 MB 1.8 MB/s eta 0:00:44
   -------- ------------------------------- 22.3/100.2 MB 1.8 MB/s eta 0:00:44
   --------- ------------------------------ 22.8/100.2 MB 1.7 MB/s eta 0:00:45
   --------- ------------------------------ 23.1/100.2 MB 1.7 MB/s eta 0:00:46
   --------- ------------------------------ 23.3/100.2 MB 1.7 MB/s eta 0:00:45
   --------- ------------------------------ 23.9/100.2 MB 1.7 MB/s eta 0:00:45
   --------- ------------------------------ 24.1/100.2 MB 1.7 MB/s eta 0:00:45
   --------- ------------------------------ 24.4/100.2 MB 1.7 MB/s eta 0:00:45
   --------- ------------------------------ 24.4/100.2 MB 1.7 MB/s eta 0:00:45
   --------- ------------------------------ 24.6/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 25.2/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 25.4/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 25.7/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 26.0/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 26.2/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 26.5/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 26.7/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 27.3/100.2 MB 1.7 MB/s eta 0:00:44
   ----------- ---------------------------- 27.8/100.2 MB 1.7 MB/s eta 0:00:44
   ----------- ---------------------------- 27.8/100.2 MB 1.7 MB/s eta 0:00:44
   ----------- ---------------------------- 28.3/100.2 MB 1.7 MB/s eta 0:00:44
   ----------- ---------------------------- 28.8/100.2 MB 1.7 MB/s eta 0:00:43
   ----------- ---------------------------- 29.4/100.2 MB 1.7 MB/s eta 0:00:43
   ------------ --------------------------- 30.1/100.2 MB 1.7 MB/s eta 0:00:42
   ------------ --------------------------- 30.7/100.2 MB 1.7 MB/s eta 0:00:41
   ------------ --------------------------- 31.2/100.2 MB 1.7 MB/s eta 0:00:40
   ------------ --------------------------- 31.7/100.2 MB 1.7 MB/s eta 0:00:40
   ------------ --------------------------- 32.2/100.2 MB 1.7 MB/s eta 0:00:39
   ------------- -------------------------- 33.0/100.2 MB 1.8 MB/s eta 0:00:39
   ------------- -------------------------- 33.6/100.2 MB 1.8 MB/s eta 0:00:38
   ------------- -------------------------- 33.8/100.2 MB 1.8 MB/s eta 0:00:38
   ------------- -------------------------- 34.1/100.2 MB 1.8 MB/s eta 0:00:38
   ------------- -------------------------- 34.6/100.2 MB 1.8 MB/s eta 0:00:38
   ------------- -------------------------- 34.9/100.2 MB 1.8 MB/s eta 0:00:37
   -------------- ------------------------- 35.4/100.2 MB 1.8 MB/s eta 0:00:37
   -------------- ------------------------- 35.9/100.2 MB 1.8 MB/s eta 0:00:37
   -------------- ------------------------- 36.4/100.2 MB 1.8 MB/s eta 0:00:36
   -------------- ------------------------- 37.0/100.2 MB 1.8 MB/s eta 0:00:36
   -------------- ------------------------- 37.5/100.2 MB 1.8 MB/s eta 0:00:35
   --------------- ------------------------ 38.3/100.2 MB 1.8 MB/s eta 0:00:35
   --------------- ------------------------ 38.8/100.2 MB 1.8 MB/s eta 0:00:34
   --------------- ------------------------ 39.3/100.2 MB 1.8 MB/s eta 0:00:34
   ---------------- ----------------------- 40.1/100.2 MB 1.9 MB/s eta 0:00:33
   ---------------- ----------------------- 40.6/100.2 MB 1.9 MB/s eta 0:00:33
   ---------------- ----------------------- 41.2/100.2 MB 1.9 MB/s eta 0:00:32
   ---------------- ----------------------- 41.4/100.2 MB 1.9 MB/s eta 0:00:32
   ---------------- ----------------------- 42.2/100.2 MB 1.9 MB/s eta 0:00:31
   ----------------- ---------------------- 42.7/100.2 MB 1.9 MB/s eta 0:00:31
   ----------------- ---------------------- 43.3/100.2 MB 1.9 MB/s eta 0:00:31
   ----------------- ---------------------- 44.0/100.2 MB 1.9 MB/s eta 0:00:30
   ----------------- ---------------------- 44.6/100.2 MB 1.9 MB/s eta 0:00:30
   ------------------ --------------------- 45.4/100.2 MB 1.9 MB/s eta 0:00:29
   ------------------ --------------------- 45.9/100.2 MB 1.9 MB/s eta 0:00:29
   ------------------ --------------------- 46.1/100.2 MB 1.9 MB/s eta 0:00:29
   ------------------ --------------------- 46.7/100.2 MB 1.9 MB/s eta 0:00:28
   ------------------ --------------------- 47.2/100.2 MB 1.9 MB/s eta 0:00:28
   ------------------- -------------------- 47.7/100.2 MB 1.9 MB/s eta 0:00:28
   ------------------- -------------------- 48.2/100.2 MB 1.9 MB/s eta 0:00:27
   ------------------- -------------------- 48.5/100.2 MB 1.9 MB/s eta 0:00:27
   ------------------- -------------------- 49.0/100.2 MB 1.9 MB/s eta 0:00:27
   ------------------- -------------------- 49.8/100.2 MB 2.0 MB/s eta 0:00:26
   ------------------- -------------------- 50.1/100.2 MB 2.0 MB/s eta 0:00:26
   -------------------- ------------------- 50.6/100.2 MB 2.0 MB/s eta 0:00:26
   -------------------- ------------------- 51.1/100.2 MB 2.0 MB/s eta 0:00:26
   -------------------- ------------------- 51.9/100.2 MB 2.0 MB/s eta 0:00:25
   -------------------- ------------------- 52.4/100.2 MB 2.0 MB/s eta 0:00:25
   --------------------- ------------------ 53.0/100.2 MB 2.0 MB/s eta 0:00:24
   --------------------- ------------------ 53.5/100.2 MB 2.0 MB/s eta 0:00:24
   --------------------- ------------------ 54.0/100.2 MB 2.0 MB/s eta 0:00:24
   --------------------- ------------------ 55.1/100.2 MB 2.0 MB/s eta 0:00:23
   ---------------------- ----------------- 55.6/100.2 MB 2.0 MB/s eta 0:00:23
   ---------------------- ----------------- 56.4/100.2 MB 2.0 MB/s eta 0:00:22
   ---------------------- ----------------- 56.9/100.2 MB 2.0 MB/s eta 0:00:22
   ----------------------- ---------------- 57.7/100.2 MB 2.0 MB/s eta 0:00:21
   ----------------------- ---------------- 58.5/100.2 MB 2.1 MB/s eta 0:00:21
   ----------------------- ---------------- 59.2/100.2 MB 2.1 MB/s eta 0:00:20
   ----------------------- ---------------- 59.8/100.2 MB 2.1 MB/s eta 0:00:20
   ------------------------ --------------- 60.3/100.2 MB 2.1 MB/s eta 0:00:20
   ------------------------ --------------- 61.1/100.2 MB 2.1 MB/s eta 0:00:19
   ------------------------ --------------- 61.6/100.2 MB 2.1 MB/s eta 0:00:19
   ------------------------ --------------- 62.4/100.2 MB 2.1 MB/s eta 0:00:18
   ------------------------- -------------- 63.2/100.2 MB 2.1 MB/s eta 0:00:18
   ------------------------- -------------- 64.0/100.2 MB 2.1 MB/s eta 0:00:18
   ------------------------- -------------- 65.0/100.2 MB 2.2 MB/s eta 0:00:17
   -------------------------- ------------- 66.1/100.2 MB 2.2 MB/s eta 0:00:16
   -------------------------- ------------- 67.1/100.2 MB 2.2 MB/s eta 0:00:16
   -------------------------- ------------- 67.6/100.2 MB 2.2 MB/s eta 0:00:15
   --------------------------- ------------ 68.2/100.2 MB 2.2 MB/s eta 0:00:15
   --------------------------- ------------ 68.7/100.2 MB 2.2 MB/s eta 0:00:15
   --------------------------- ------------ 68.7/100.2 MB 2.2 MB/s eta 0:00:15
   --------------------------- ------------ 69.2/100.2 MB 2.2 MB/s eta 0:00:14
   --------------------------- ------------ 69.5/100.2 MB 2.2 MB/s eta 0:00:14
   --------------------------- ------------ 69.7/100.2 MB 2.2 MB/s eta 0:00:14
   --------------------------- ------------ 70.0/100.2 MB 2.2 MB/s eta 0:00:14
   ---------------------------- ----------- 70.5/100.2 MB 2.2 MB/s eta 0:00:14
   ---------------------------- ----------- 70.5/100.2 MB 2.2 MB/s eta 0:00:14
   ---------------------------- ----------- 70.8/100.2 MB 2.2 MB/s eta 0:00:14
   ---------------------------- ----------- 71.0/100.2 MB 2.2 MB/s eta 0:00:14
   ---------------------------- ----------- 71.3/100.2 MB 2.2 MB/s eta 0:00:14
   ---------------------------- ----------- 71.8/100.2 MB 2.2 MB/s eta 0:00:13
   ---------------------------- ----------- 72.1/100.2 MB 2.2 MB/s eta 0:00:13
   ---------------------------- ----------- 72.4/100.2 MB 2.2 MB/s eta 0:00:13
   ----------------------------- ---------- 72.9/100.2 MB 2.2 MB/s eta 0:00:13
   ----------------------------- ---------- 73.1/100.2 MB 2.2 MB/s eta 0:00:13
   ----------------------------- ---------- 73.7/100.2 MB 2.2 MB/s eta 0:00:13
   ----------------------------- ---------- 74.2/100.2 MB 2.2 MB/s eta 0:00:12
   ----------------------------- ---------- 74.7/100.2 MB 2.2 MB/s eta 0:00:12
   ------------------------------ --------- 75.5/100.2 MB 2.2 MB/s eta 0:00:12
   ------------------------------ --------- 76.0/100.2 MB 2.2 MB/s eta 0:00:11
   ------------------------------ --------- 76.5/100.2 MB 2.2 MB/s eta 0:00:11
   ------------------------------ --------- 77.3/100.2 MB 2.2 MB/s eta 0:00:11
   ------------------------------- -------- 77.9/100.2 MB 2.2 MB/s eta 0:00:10
   ------------------------------- -------- 78.4/100.2 MB 2.3 MB/s eta 0:00:10
   ------------------------------- -------- 79.2/100.2 MB 2.3 MB/s eta 0:00:10
   ------------------------------- -------- 80.0/100.2 MB 2.3 MB/s eta 0:00:09
   -------------------------------- ------- 80.7/100.2 MB 2.3 MB/s eta 0:00:09
   -------------------------------- ------- 81.5/100.2 MB 2.3 MB/s eta 0:00:09
   -------------------------------- ------- 82.1/100.2 MB 2.3 MB/s eta 0:00:08
   -------------------------------- ------- 82.6/100.2 MB 2.3 MB/s eta 0:00:08
   --------------------------------- ------ 83.1/100.2 MB 2.3 MB/s eta 0:00:08
   --------------------------------- ------ 83.9/100.2 MB 2.3 MB/s eta 0:00:08
   --------------------------------- ------ 84.7/100.2 MB 2.3 MB/s eta 0:00:07
   ---------------------------------- ----- 85.2/100.2 MB 2.3 MB/s eta 0:00:07
   ---------------------------------- ----- 86.2/100.2 MB 2.3 MB/s eta 0:00:06
   ---------------------------------- ----- 86.8/100.2 MB 2.4 MB/s eta 0:00:06
   ---------------------------------- ----- 87.6/100.2 MB 2.4 MB/s eta 0:00:06
   ----------------------------------- ---- 88.3/100.2 MB 2.4 MB/s eta 0:00:05
   ----------------------------------- ---- 88.9/100.2 MB 2.4 MB/s eta 0:00:05
   ----------------------------------- ---- 89.7/100.2 MB 2.4 MB/s eta 0:00:05
   ----------------------------------- ---- 90.2/100.2 MB 2.4 MB/s eta 0:00:05
   ------------------------------------ --- 91.0/100.2 MB 2.4 MB/s eta 0:00:04
   ------------------------------------ --- 91.8/100.2 MB 2.4 MB/s eta 0:00:04
   ------------------------------------ --- 92.3/100.2 MB 2.4 MB/s eta 0:00:04
   ------------------------------------ --- 92.5/100.2 MB 2.4 MB/s eta 0:00:04
   ------------------------------------- -- 92.8/100.2 MB 2.4 MB/s eta 0:00:04
   ------------------------------------- -- 93.3/100.2 MB 2.4 MB/s eta 0:00:03
   ------------------------------------- -- 93.8/100.2 MB 2.4 MB/s eta 0:00:03
   ------------------------------------- -- 94.4/100.2 MB 2.4 MB/s eta 0:00:03
   ------------------------------------- -- 94.9/100.2 MB 2.5 MB/s eta 0:00:03
   -------------------------------------- - 95.4/100.2 MB 2.5 MB/s eta 0:00:02
   -------------------------------------- - 95.9/100.2 MB 2.5 MB/s eta 0:00:02
   -------------------------------------- - 96.2/100.2 MB 2.5 MB/s eta 0:00:02
   -------------------------------------- - 96.7/100.2 MB 2.5 MB/s eta 0:00:02
   -------------------------------------- - 97.0/100.2 MB 2.5 MB/s eta 0:00:02
   -------------------------------------- - 97.5/100.2 MB 2.5 MB/s eta 0:00:02
   ---------------------------------------  98.0/100.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  98.6/100.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  99.1/100.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  99.6/100.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 2.5 MB/s  0:00:44
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]

In [9]:
from catboost import CatBoostRegressor
Regressor=CatBoostRegressor(iterations=50,random_state=0)
Regressor=Regressor.fit(x_train,y_train)

Learning rate set to 0.462784
0:	learn: 8076.0991789	total: 139ms	remaining: 6.8s
1:	learn: 6122.3808832	total: 143ms	remaining: 3.42s
2:	learn: 5228.8880293	total: 148ms	remaining: 2.31s
3:	learn: 4855.3649438	total: 151ms	remaining: 1.73s
4:	learn: 4696.0404617	total: 155ms	remaining: 1.39s
5:	learn: 4585.4188470	total: 160ms	remaining: 1.17s
6:	learn: 4528.0167399	total: 208ms	remaining: 1.28s
7:	learn: 4468.6958952	total: 248ms	remaining: 1.3s
8:	learn: 4414.0379472	total: 274ms	remaining: 1.25s
9:	learn: 4385.0619171	total: 294ms	remaining: 1.17s
10:	learn: 4360.3064903	total: 319ms	remaining: 1.13s
11:	learn: 4320.2501897	total: 343ms	remaining: 1.08s
12:	learn: 4293.7642619	total: 351ms	remaining: 998ms
13:	learn: 4260.9734534	total: 358ms	remaining: 921ms
14:	learn: 4231.2541015	total: 371ms	remaining: 865ms
15:	learn: 4190.6845731	total: 416ms	remaining: 885ms
16:	learn: 4176.1132717	total: 432ms	remaining: 839ms
17:	learn: 4145.8197699	total: 477ms	remaining: 848ms
18:	learn: 4108.6088470	total: 516ms	remaining: 841ms
19:	learn: 4090.5964130	total: 519ms	remaining: 779ms
20:	learn: 4058.5501684	total: 523ms	remaining: 722ms
21:	learn: 4044.0080425	total: 529ms	remaining: 673ms
22:	learn: 4021.5696774	total: 576ms	remaining: 677ms
23:	learn: 3994.0413117	total: 617ms	remaining: 669ms
24:	learn: 3969.7875784	total: 628ms	remaining: 628ms
25:	learn: 3951.7804569	total: 651ms	remaining: 601ms
26:	learn: 3940.3370002	total: 656ms	remaining: 558ms
27:	learn: 3925.6995663	total: 662ms	remaining: 520ms
28:	learn: 3906.0549276	total: 665ms	remaining: 481ms
29:	learn: 3885.9999541	total: 667ms	remaining: 445ms
30:	learn: 3868.8410898	total: 669ms	remaining: 410ms
31:	learn: 3842.4330284	total: 672ms	remaining: 378ms
32:	learn: 3811.2693388	total: 674ms	remaining: 347ms
33:	learn: 3803.4129600	total: 677ms	remaining: 318ms
34:	learn: 3741.4515262	total: 679ms	remaining: 291ms
35:	learn: 3732.8904490	total: 684ms	remaining: 266ms
36:	learn: 3718.8417858	total: 688ms	remaining: 242ms
37:	learn: 3706.9535105	total: 691ms	remaining: 218ms
38:	learn: 3693.1490983	total: 693ms	remaining: 196ms
39:	learn: 3684.2121764	total: 696ms	remaining: 174ms
40:	learn: 3657.1978068	total: 698ms	remaining: 153ms
41:	learn: 3641.8711421	total: 700ms	remaining: 133ms
42:	learn: 3614.1470454	total: 703ms	remaining: 114ms
43:	learn: 3601.4775967	total: 705ms	remaining: 96.2ms
44:	learn: 3568.9476006	total: 708ms	remaining: 78.7ms
45:	learn: 3542.7566624	total: 714ms	remaining: 62.1ms
46:	learn: 3532.1511923	total: 717ms	remaining: 45.7ms
47:	learn: 3492.1307293	total: 719ms	remaining: 30ms
48:	learn: 3468.6025783	total: 722ms	remaining: 14.7ms
49:	learn: 3441.0505434	total: 765ms	remaining: 0us

In [10]:
y_pred=Regressor.predict(x_test)

In [11]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [12]:
r_score

0.8804802547915455